sudo: required
dist: trusty

language: node_js

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

install:
- nvm install 6
- npm install electron-builder # force install next version to test electron-builder
- npm install
- npm prune

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
